### ISSUE TITLE
Example flow?

### ISSUE THREAD

**Issue by johnwalicki** [sax1johno/node-red-contrib-http-multipart#4]
I've read the google groups forum posts about node-red-contrib-http-multipart
[1](https://groups.google.com/forum/#!topic/node-red/wVreRiBOoJ4)
[2](https://groups.google.com/forum/#!topic/node-red/NVDi0ko-qs0)

I even saw a good discussion / snippet on [StackOverflow](http://stackoverflow.com/questions/40390822/in-node-red-how-do-i-upload-to-a-node-with-the-given-configuration-and-retrieve)

I haven't found an example flow however that uses node-red-contrib-http-multipart
Is there an example anywhere?
Thanks!  -- John

**Comment by sax1johno** [comment]
Hey there @johnwalicki 

Sure - I put together some flows for a previously closed ticket.

https://github.com/sax1johno/node-red-contrib-http-multipart/issues/2

In that one, I address a few common issues including how the "fields" object and one issue that can arise with file uploads from web-based forms.  I also have a few flows in there (the last one posted is tested - I'll post that below).

**Comment by sax1johno** [comment]
The flow below should get you started.  It also has a form built in that contains the necessary components for uploading a file.

```
[
    {
        "id": "e1437202.08b6f",
        "type": "httpInMultipart",
        "z": "901f2c7a.fe432",
        "name": "",
        "url": "/test/upload",
        "method": "post",
        "fields": "[ { \"name\": \"myFile\", \"maxCount\": 1} ]",
        "swaggerDoc": "",
        "x": 166,
        "y": 255.88888454437256,
        "wires": [
            [
                "97128846.4a6f08",
                "da06fce1.4d19d",
                "27884dc6.4df142"
            ]
        ]
    },
    {
        "id": "27884dc6.4df142",
        "type": "function",
        "z": "901f2c7a.fe432",
        "name": "",
        "func": "var files = msg.req.files;\nmsg.files = Object.keys(files);\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 419,
        "y": 169.88888454437256,
        "wires": [
            [
                "86f505f5.30b1e8"
            ]
        ]
    },
    {
        "id": "b0f918ce.721f48",
        "type": "http in",
        "z": "901f2c7a.fe432",
        "name": "",
        "url": "/test/send",
        "method": "get",
        "swaggerDoc": "",
        "x": 156.1111183166504,
        "y": 445,
        "wires": [
            [
                "915ef62b.bfb358"
            ]
        ]
    },
    {
        "id": "915ef62b.bfb358",
        "type": "template",
        "z": "901f2c7a.fe432",
        "name": "",
        "field": "payload",
        "fieldType": "msg",
        "format": "handlebars",
        "syntax": "mustache",
        "template": "<form action=\"/test/upload\" method=\"POST\" enctype=\"multipart/form-data\">\n    <input type=\"file\" name=\"myFile\" />\n    <input type=\"submit\" value=\"Submit\">\n</form>",
        "x": 346.1111183166504,
        "y": 445,
        "wires": [
            [
                "14764b85.9291b4"
            ]
        ]
    },
    {
        "id": "14764b85.9291b4",
        "type": "http response",
        "z": "901f2c7a.fe432",
        "name": "",
        "x": 696.1111183166504,
        "y": 445,
        "wires": []
    },
    {
        "id": "86f505f5.30b1e8",
        "type": "debug",
        "z": "901f2c7a.fe432",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "true",
        "x": 626.1111183166504,
        "y": 165,
        "wires": []
    },
    {
        "id": "97128846.4a6f08",
        "type": "debug",
        "z": "901f2c7a.fe432",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "true",
        "x": 386.1111183166504,
        "y": 285,
        "wires": []
    },
    {
        "id": "da06fce1.4d19d",
        "type": "http response",
        "z": "901f2c7a.fe432",
        "name": "",
        "x": 676,
        "y": 275.88888454437256,
        "wires": []
    }
]
```

**Comment by ghost** [comment]
Hi, I tried this example flow, tried it once, and was surprised to see how well it works, after uploading successfully using http://hostname:1880/test/upload. Then I started fiddling around, wanted to see what happens if I hit http://hostname:1880/test/send on browser, and since it stopped working. I restarted NR, even removed node-red-contrib-http-multipart, rebooted, re-installed, removed and installed the example flow, but cannot get it to work again. Any ideas?

**Comment by ghost** [comment]
When visiting the /test/upload page, it just says:
`Cannot GET /test/upload`

**Comment by ghost** [comment]
I now visited site /test/send - uploaded the file, and it worked.... not sure if this is correct .....

**Comment by sax1johno** [comment]
@jroux1 can you post the flow and the form that you're having trouble with?

**Comment by ghost** [comment]
All working now, thank you ! Awesome piece of tech !
